### ISSUE TITLE
wow!同学你好，这个页面可以说非常干净清爽了！

### ISSUE THREAD

**Issue by KamenRider41** [linjunc/linjunc.github.io#7]
我看同学也没用直接使用其他主题，那么是如何去diy页面的呢？或者说如何去打造自己的主题呢，可以在博客出教程吗，就是比如如何去修改默认主题的排版之类的。

**Comment by linjunc** [comment]
hello, 目前正在聚焦于 blog 内容的书写，后续（不久后）会出 blog 教程，可以留意这个仓库的 readme，后续会做更新
